baseURL = "https://blog.spatocode.com/"
languageCode = "en-us"
title = "Kene's Blog"
theme = "bootstrap4-blog"
copyright = "Copyright (c) 2020 Ekene Izukanne"
disqusShortname = "blog-spatocode-com"

[[menu.sidebar]]
  name = "Website"
  weight = 1
  url = "https://www.spatocode.com"

[[menu.sidebar]]
  name = "Github"
  weight = 2
  url = "https://www.github.com/spatocode"

[[menu.sidebar]]
  name = "Twitter"
  weight = 3
  url = "https://www.twitter.com/spatocode"

[[menu.sidebar]]
  name = "Facebook"
  weight = 4
  url = "https://www.facebook.com/spatocode"

[params]
  # Site author
  author = "Ekene Izukanne"

  # Description/subtitle for homepage (can be Markdown)
  description = "Sharing my knowledge and thoughts with words."

  # Show header (default: true)
  #header_visible = true

  favicon = "/favicon.ico"

  # Format dates with Go's time formatting
  date_format = "Mon Jan 02, 2006"

  googleAnalytics = "UA-167517723-2"

  # verification string for Google Webmaster Tools
  #google_verify_meta = "BAi57DROASu4b2mkVNA_EyUsobfA7Mq8BmSg7Rn-Zp9"

  # verification string for Bing Webmaster Tools
  #bing_verify_meta = "3DA353059F945D1AA256B1CD8A3DA847"

  # verification string for Yandex Webmaster Tools
  #yandex_verify_meta = "66b077430f35f04a"

  # Optionally display a message about the site's use of cookies, which may be
  # required for your site in the European Union. Set the parameter below to a
  # page where the user can get more information about cookies, either on your
  # site or externally, for example:
  #cookie_consent_info_url = "/cookie-information/"
  #cookie_consent_info_url = "http://cookiesandyou.com"

  # show sharing icons on pages/posts (default: true)
  #sharingicons = true

  # Display post summaries instead of content in list templates (default: true)
  #truncate = true

  # Disable the use of sub-resource integrity on CSS/JS assets (default: false)
  # Useful if you're using a CDN or other host where you can't control cache headers
  #disable_sri = false

  [params.sidebar]
    # Optional about block for sidebar (can be Markdown)
    about = "Articles on Software Engineering and more. All articles are written by [Ekene Izukanne](https://www.spatocode.com/about), Software Developer and Open Sourcerer."

    # How many posts to show on the sidebar (Default: 5)
    #num_recent_posts = 2

  [params.social]
    # Optional, used for attribution in Twitter cards (ideally not a person
    # for example: nytimes, flickr, NatGeo, etc).
    # See: https://dev.twitter.com/cards/types/summary-large-image
    twitter = "username"

# Default content language for Hugo 0.17's multilingual support (default is "en")
# See: https://github.com/spf13/hugo/blob/master/docs/content/content/multilingual.md
#DefaultContentLanguage = "en"

# Languages to render
#[languages.en]
#[languages.bg]
  # Bulgarian date format is dd.mm.yyyy
  #date_format = "02.01.2006"

# vim: ts=2 sw=2 et